
export const common = {
    RESET : "RESET",
    APPLICATION_FORM_RESET : 'APPLICATION_FORM_RESET',
    UPDATE_APPLICATION_STAGES : 'UPDATE_APPLICATION_STAGES',
    UPDATE_SYMR_MASTER_DATA:'UPDATE_SYMR_MASTER_DATA',
    UPDATE_IA_MASTER_DATA:'UPDATE_IA_MASTER_DATA',
    UPDATE_IE_MASTER_DATA:'UPDATE_IE_MASTER_DATA',
    UPDATE_PC_MASTER_DATA : 'UPDATE_PC_MASTER_DATA',
    RESET_APPLICATION_DETAIL : 'RESET_APPLICATION_DETAIL',
    RESET_STAFF_DETAILS : 'RESET_STAFF_DETAILS'
}

